apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: es-cluster-flow
spec:
  match:
     - select:
        namespaces: ["production"]
  globalOutputRefs:
    - es-cluster-output