apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: es-cluster-flow
spec:
  filters:
    - record_transformer:
       remove_keys: kubernetes
  match:
     - select:
        namespaces: ["streaming", "production"]
  globalOutputRefs:
    - es-cluster-output