apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: es-cluster-flow
spec:
  match:
     - select:
        namespaces:
          - "streaming"
          - "production"
     - exclude: 
        labels:
          app: coturn
  globalOutputRefs:
    - es-cluster-output