apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: es-cluster-output
spec:
  elasticsearch:
    host: quickstart-es-http.logging.svc.cluster.local
    include_timestamp: true
    reconnect_on_error: true
    reload_on_failure: true
    reload_connections: true
    include_tag_key: true
    logstash_format: true
    logstash_prefix: fluentd
    index_name: fluentd
    logstash_dateformat:  '%Y.%m.%d'
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elastic
    password:
      valueFrom:
        secretKeyRef:
          name: quickstart-es-elastic-user
          key: elastic
    buffer:
      timekey_use_utc: true
      chunk_limit_size: 32MB
      total_limit_size: 12288MB
      type: file
      path: "/fluentd/log/elastic-buffer"
      flush_thread_count: 8
      flush_interval: "1s"
      queue_limit_length: 4
      flush_mode: interval
      retry_max_interval: "30"
      retry_forever: true

