apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: es-cluster-output
spec:
  enabledNamespaces: ["production"]
  # file:   // add type file for debugging 
  #   path: /tmp/logs/${tag}/%Y/%m/%d.%H.%M
  #   append: true
  #   buffer:
  #     timekey: 1m
  #     timekey_wait: 10s
  #     timekey_use_utc: true
  elasticsearch:
    host: quickstart-es-http.logging.svc.cluster.local
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elastic
    password:
      valueFrom:
        secretKeyRef:
          name: quickstart-es-elastic-user
          key: elastic
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true