apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search-quickstart
  namespace: logging
spec:
  version: 8.5.3
  count: 1
  elasticsearchRef:
    name: quickstart