apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  namespace: logging  
data:
  action_file.yml: |-
    actions:
      1:
        action: delete_indices
        description: >-
          Delete indices older than 45 days (based on index name), for logstash-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          allow_ilm_indices: true
          ignore_empty_list: True
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: '^(fluentd).*$'
        - filtertype: age
          source: creation_date
          direction: older
          unit: days
          unit_count: 30
  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - quickstart-es-http.logging.svc.cluster.local
      port: 9200
      url_prefix:
      use_ssl: True
      certificate:
      client_cert:
      client_key:
      aws_key:
      aws_secret_key:
      aws_region:
      ssl_no_validate: True
      http_auth: elastic:P8MD80IoD1z1C9BC8Uk72HQ6
      timeout: 30
      master_only: False

    logging:
      loglevel: DEBUG
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']