apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: es-flow
  namespace: logging
spec:
  filters:
    - dedot:
        de_dot_separator: "-"
        de_dot_nested: true
    - parser:
        remove_key_name_field: true
        parse:
          type: nginx
    - tag_normaliser:
        format: ${namespace_name}.${pod_name}.${container_name}
  match:
     - select: {}
  localOutputRefs:
    - es-output
