apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: logging
spec:
  version: 8.4.2
  count: 1
  elasticsearchRef:
    name: "quickstart"
  http:
    service: 
      spec:
        type: NodePort
    tls: 
      selfSignedCertificate:
        disabled: true    
  #http:
  #  service:
  #    spec:
  #      type: LoadBalancer
  # this shows how to customize the Kibana pod
  # with labels and resource limits
  podTemplate:
    metadata:
      labels:
        foo: bar
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: "managed-ng-logging"         
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1