apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: logging
spec:
  version: 7.10.0
  count: 1
  podTemplate:
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: "managed-ng-logging"         
      containers:
      - name: kibana
        resources:
          limits:
            memory: 2Gi
            cpu: 1
  elasticsearchRef:
    name: quickstart
  http:
    service: 
      spec:
        type: NodePort
    tls: 
      selfSignedCertificate:
        disabled: true
