apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: logging
spec:
  version: 7.10.0
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    service: 
      spec:
        type: NodePort
    tls: 
      selfSignedCertificate:
        disabled: true
