
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-simple
  namespace: logging
spec:
  fluentd:
    resources:
      limits:
          memory: 2000Mi
      requests:
          cpu: 100m
          memory: 200Mi
  fluentbit: {}
  controlNamespace: logging
  watchNamespaces: ["production", "streaming"]