apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-simple
spec:
  # defaultFlow:
  #   filters:
  #      - dedot:
  #         de_dot_nested: true
  #         de_dot_separator: "-"

  fluentd:
    logLevel: debug
  fluentbit: 
    extraVolumeMounts:
    - source: /opt/docker
      destination: /opt/docker
      readOnly: true
  controlNamespace: logging
  watchNamespaces: ["production", "streaming"]