apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-simple
  namespace: logging-test
spec:
  fluentd: {}
  fluentbit: {}
  enableRecreateWorkloadOnImmutableFieldChange: true
  controlNamespace: logging-test