apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-simple
  namespace: logging-test
spec:
  fluentd: {}
  fluentbit:
    image:
      pullPolicy: Always
      repository: fluent/fluent-bit
      tag: 1.3.2-debug
  enableRecreateWorkloadOnImmutableFieldChange: true
  controlNamespace: logging-test