apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: kube-system
data:
  elasticsearch.yml: |
    cluster.name: elastic-cluster
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.seed_hosts: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch"
    cluster.initial_master_nodes: "es-cluster-0,es-cluster-1"
